version: '3'
services:
  tgtg-alerts:
    image: ghcr.io/josxha/tgtg-alerts:latest
    container_name: tgtg-alerts
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: <bot_token>
      TELEGRAM_CHAT_ID: <chat_id>
      TGTG_ACCESS_TOKEN: <access_token>
      TGTG_REFRESH_TOKEN: <refresh_token>
      TGTG_USER_ID: <user_id>
      TGTG_COOKIE: <cookie>
      #INTERVAL: 60 # optional, in seconds, default: 60
    volumes:
      # the file ./cache.log must already exist on the host
      - ./cache.log:/app/cache.log
