name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    name: Build image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . \
          --tag ghcr.io/josxha/tgtg-alerts:${{ github.sha }} \
          --tag ghcr.io/josxha/tgtg-alerts:latest
      - name: Push the Docker image
        run: docker push ghcr.io/josxha/tgtg-alerts --all-tags
